# -*- coding: utf-8 -*-
"""exemplos_estatistica.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bqwy98_QbWCDxg5wqdgBa8C5tsV8HiEk
"""

import pandas as pd
import numpy as np
from scipy import stats
import statistics as sts
import matplotlib.pyplot as plt

"""# Criando uma lista de dados para realizar cálculos estatísticos."""

dados=[1,2,3,3,3,4,5,5,5,5,6,7,8,8,9,10]

"""calculando média aritmética, desvio padrão, variância, mediana e moda."""

valor_médio=sts.mean(dados)
print(valor_médio)

desvio_padrão=sts.stdev(dados)
print(desvio_padrão)

variância=sts.variance(dados)
print(variância)

mediana=sts.median(dados)
print(mediana)

moda=sts.mode(dados)
print(moda)

"""Gerando o histograma dos dados."""

plt.hist(dados,5,rwidth=0.9)
plt.show





